spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/command}
    username: ${SPRING_DATASOURCE_USERNAME:app_command}
    password: ${SPRING_DATASOURCE_PASSWORD:app_command}
